### PR TITLE
savemanager object. subparser for modifications. all currencies added (using the currency file)

### PR DESCRIPTION
**Pull request by unixtreme**
This is not an actual pull request more like a ping so that you can review this, we have duplicated some work so if there's anything here that you think can be handy then pull it.
I particularly like seggregating the settings on a settings file as well as the save_manager module with a SaveData object where the account and heroes live, that can handle modifications and push changes (if any).

### CODE REVIEW

**Comment by VisualStudio-zz** [comment]
I update it to the latest commit on the main branch and I'll pull it.

**Comment by unixtreme** [comment]
didn't look much at the conflicts, as I'm considering making a basic GUI next... I saw you added new options, in my case I decided to make them dynamic based on the contents of CURRENCY_LIST but not sure if that approach is good.

**Comment by VisualStudio-zz** [comment]
I honestly don't know why I didn't do a GUI, I know C# like the back of my hand I just like working with python more.

**Comment by VisualStudio-zz** [comment]
IDK how to pull to another branch. I made a GUI branch so you could work on the GUI for it.

**Pull request closed without merging**
